export const relationsListPositions = [
  {
    title: "Дачыненне на Android",
    url: "https://play.google.com/store/apps/details?id=by.dabravesce",
    extraClasses: "fa-android",
    fullText: "Android-дачыненне",
    briefText: "Android",
  },
  {
    title: "Група ў Twitter",
    url: "https://twitter.com/dabravesce",
    extraClasses: "fa-twitter",
    fullText: "Група ў Twitter",
    briefText: "Twitter",
  },
  {
    title: "Група на Facebook",
    // url: "https://www.facebook.com/groups/dabravesce",
    url: "https://www.facebook.com/groups/396324350426582/",
    extraClasses: "fa-facebook",
    fullText: "Група на Facebook",
    briefText: "Facebook",
  },
  // {
  //   title: "Канал у Telegram",
  //   url: "https://t.me/s/evangellie",
  //   extraClasses: "fa-telegram",
  //   fullText: "Канал у ",
  //   briefText: "Telegram",
  // },
  {
    title: "Тэлефон",
    url: "tel:+375172269815",
    extraClasses: "fa-phone",
    fullText: "Кантактны тэлефон",
    briefText: "Тэлефон",
  },
  {
    title: "Рэпазіторый на Gihub",
    url: "https://github.com/Vorvule/dabravesce-react",
    extraClasses: "fa-github",
    fullText: "Github-рэпазіторый",
    briefText: "Github",
  },
  {
    title: "Электронная пошта",
    url: "mailto:bpbtvm@tut.by",
    extraClasses: "fa-envelope-open-o",
    fullText: "Электронная пошта",
    briefText: "Пошта",
  },
];
